name: Eli
markdown: redcarpet
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json",  "README.md", "_scripts", "_scss", "gemfile", "Gemfile.lock"]
url: "https://elisweb.co.uk"

destination: docs

collections:
  works:
    output: true

  posts:
    output:   true

permalink: /blog/:title/
